name: Delete branch

on:
  pull_request:
    types: [closed]

jobs:
  lokalise-delete-branch:
    if: github.event.pull_request.merged == true # If the PR is closed but not merged, skip this job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump step context
        env:
          STEP_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEP_CONTEXT"

      - name: Git branch all
        run: git branch --all

      - name: Deleted Branch
        run: |
          BRANCH_NAME=${{ steps.get_commits.outputs.base_commit }}
          echo $BRANCH_NAME

      - name: Git branch all
        run: git branch --all

      - name: Git diff
        run: git diff --name-only origin/develop -- "**/locales/*.properties"

      - name: Git diff
        run: git diff --name-only "${{ steps.get_commits.outputs.base_commit }}..origin/develop" -- "**/locales/*.properties"
