name: Delete branch

on:
  delete:
    branches:
      - '*'

jobs:
  lokalise-delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Deleted Branch
        run: |
          BRANCH_NAME=${{ github.event.ref }}
          echo "$BRANCH_NAME"
