name: Check no diff

on: [pull_request]

jobs:
  check-no-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump GitHub context
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          echo $BRANCH_NAME
          ./echo_arguments.sh $BRANCH_NAME

      - name: Make change
        run: touch new_file.txt

      - name: Make change
        run: echo "hello" >> file.txt

      - name: git diff
        run: git diff --name-only --exit-code || true

      - name: git add
        run: git add -N .

      - name: git diff
        run: git diff --name-only --exit-code || true

      - name: Git diff
        run: git diff --exit-code