name: Compare PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  compare-files-after-pr-merge:
    if: github.event.pull_request.merged == true # If the PR is closed but not merged, skip this job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get base and head commits
        id: get_commits
        run: |
          echo "Base commit: ${{ github.event.pull_request.base.sha }}"
          echo "Head commit: ${{ github.event.pull_request.head.sha }}"
          echo "::set-output name=base_commit::${{ github.event.pull_request.base.sha }}"
          echo "::set-output name=head_commit::${{ github.event.pull_request.head.sha }}"

      - name: Compare files
        run: |
          BASE_COMMIT=${{ steps.get_commits.outputs.base_commit }}
          HEAD_COMMIT=${{ steps.get_commits.outputs.head_commit }}
          git diff --name-only $BASE_COMMIT $HEAD_COMMIT > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Display file differences
        run: |
          BASE_COMMIT=${{ steps.get_commits.outputs.base_commit }}
          HEAD_COMMIT=${{ steps.get_commits.outputs.head_commit }}
          while IFS= read -r file; do
            echo "Changes in $file:"
            git diff $BASE_COMMIT $HEAD_COMMIT -- $file
          done < changed_files.txt

      - name: git diff
        run: |
          BASE_COMMIT=${{ steps.get_commits.outputs.base_commit }}
          git diff "$BASE_COMMIT..origin/develop" -- "resources/*.properties" | grep -v "_" | grep -v "tmp/"

      - name: git diff 2
        run: |
          BASE_COMMIT=${{ steps.get_commits.outputs.base_commit }}
          git diff "origin/develop..$BASE_COMMIT" -- "resources/*.properties" | grep -v "_" | grep -v "tmp/"

      - name: echo
        run: |
          DELETED_BRANCH=${{ github.base.head.ref }}
          BRANCH_NAME=${DELETED_BRANCH#refs/heads/}
          echo "$DELETED_BRANCH"
          echo "$BRANCH_NAME"